### ISSUE TITLE
2.22 should have drupal/crop:^2.0

### ISSUE THREAD

**Issue by kekkis** [acquia/lightning#514] opened 2017-11-06 17:05 UTC
https://www.drupal.org/project/crop/releases/8.x-2.0-beta1 says:

> This is the first beta release with support for the core media entity. You should only update to this version if you are using core version.

This is part of the `drush media-entity-check-upgrade` output I got:

`The following modules depend on media entity and need to be either upgraded or uninstalled: crop_media_entity.`

The module mentioned is part of `drupal/crop`.

Additionally, since `drupal/image_widget_crop` depends (in its current form) on `drupal/crop:1.x`, it needs a patch (which I just created) included which takes its dependency to the correct level as well.

**Comment by balsama** [comment] 2017-11-07 15:37
Hmm. Crop API 1.x doesn't actually have a dependency on Media Entity. As such, there aren't any changes required to it to make it compatible with Core Media. So I'm not really sure why the maintainer created a 2.x branch. Perhaps @woprrr can shed some light on that?

**Comment by kekkis** [comment] 2017-11-07 15:48
@balsama, As I wrote above (perhaps not clearly enough), the submodule Media entity crop is the one that has the dependency on Media Entity. See http://cgit.drupalcode.org/crop/tree/modules/crop_media_entity/crop_media_entity.info.yml for more detail.

**Comment by woprrr** [comment] 2017-11-07 16:16
Hi @balsama , 8.x-2.x is a branch with support for the core media entity.
You should only update to this version if you are using core version. And if you use crop with media in core that issue is for you ==> https://www.drupal.org/node/2918441

@kekkis Infact crop_media_entity isn't used ATM. In that provider the idea was that you could have crops that are tied to different entities. This way you could say for node N crop like this and for node M like this but then we realized that the image style system can't do that so it was a good idea I guess but can't be used right now.

**Comment by balsama** [comment] 2017-11-07 16:48
Thanks @woprrr and @kekkis 👍 

So Lightning _has_ migrated to the core media system. If I understand everything correctly, Crop API 1.x will work with either Core Media or Media Entity _(as evidenced by Lightning's test passing using Core Media + Crop API - and the fact that it doesn't even have a requirement on Media Entity or Core Media)_.

But Crop API has the Media Entity Crop _submodule_ which _does_ require Media Entity in the 1.x branch. And the 2.x branch requires core Media. Lightning doesn't use Media Entity Crop, but staying on the 1.x branch of Crop API will prevent others from using it.

OK. Either way, we should update, but now I understand why. Thanks.

**Comment by woprrr** [comment] 2017-11-07 16:56
Actually I admit we have lot of complexity about versions managements caused by Media migrate. IWC and Crop API not have a real dependencies with Media and others entities because both module are usable on each EntityForm/Form api context.

> So Lightning has migrated to the core media system
In that case that's better to use future 2.1 of IWC (Deploy are freeze I wait Janez analysis) and use ^2.0 of crop api. That should fixe all problems for lightning.

Another think I need to share... Actually for IWC this is not problematic to fixe the version of crop api to >= 2.0 ? If we have instance using crop 1.x and need to continue to use that version but need to change IWC to >= 2.1 that's impossible. This isn't problematic if all need to switch to core media system like lightning ...

**Comment by balsama** [comment] 2017-11-07 20:46
Unfortunately, this doesn't look like it's going to be as simple as just swapping in the 2.x branch for the 1.x branch :(
https://travis-ci.org/balsama/lightning/builds/298741199

**Comment by woprrr** [comment] 2017-11-08 09:27
I check that today @balsama But error is for media :o 

`When I visit "/admin/structure/media/add"`

**Comment by woprrr** [comment] 2017-11-08 10:45
@balsama @kekkis I just push the new 2.1 release of ImageWidgetCrop with adjusts in composer.json to maintain compatibility with 1.x AND 2.x of Crop API. Now Crop api version can be suggested by project composer.json to use (old / media entity branch 1.x) and Media core version are 2.x. Now I will test this issue more specifically and make you feedback ;)

**Comment by balsama** [comment] 2017-11-17 20:57
Fixed in 213afd204b5722c0e57cf23d72350c3b54edb37c

**Closed by balsama** 2017-11-17 20:57 UTC
