### ISSUE TITLE
Can't exclude components from subprofile

### ISSUE THREAD

**Issue by danepowell** [acquia/lightning#317] opened 2017-03-31 00:38 UTC
We should be able to exclude components of Lightning from a subprofile using an array like this in the subprofile's info.yml file:

    base profile:
      name: lightning
      excluded_dependencies:
        - lightning_layout
        - lightning_page
        - lightning_roles

However, this doesn't seem to work, at least during Drupal core configuration synchronization.

The Lightning profile is currently disabled on our site (so that we can work around this bug to keep Lightning Layout disabled). Our `core.extensions.yml` file has the lightning profile enabled, but the above modules (layout, page, roles) disabled. When we run `drush config-import`, the import fails with exceptions like this:

> Drupal\Core\Config\ConfigImporterException: There were errors validating the config synchronization. in Drupal\Core\Config\ConfigImporter->validate() (line 728 of docroot/core/lib/Drupal/Core/Config/ConfigImporter.php).
> The import failed due for the following reasons: Unable to uninstall the <em class="placeholder">Landing page</em> module since the <em class="placeholder">Lightning</em> module is installed.

**Comment by balsama** [comment] 2017-03-31 18:42
It looks like there was some logic in ConfigImportSubscriber that was missed. I also updated a few other things there to make sure you can't uninstall base profiles. All of this is in the core patch though. PR #319 just pulls in the latest patch.

**Comment by balsama** [comment] 2017-04-03 14:34
@danepowell this should be fixed. I don't have a test for this in Lightning, because it should really be covered in core's test coverage. I'm struggling to see how that will fit in over there though.

New patch has been included in HEAD of 8.x-2.x and will be released with Lightning 2.1.0 on 5 April.

**Comment by danepowell** [comment] 2017-04-03 16:17
Awesome, thanks! Will look forward to trying this on Wednesday.

**Comment by balsama** [comment] 2017-04-03 17:53
Worth noting the steps I used to test:

1. Install sub-profile of Lightning with at least one Lightning dependency excluded (e.g. dblog)
2. export core.extension.yml
3. enable the previously excluded Lightning dependency
4. import the configuration

Expected result:
- dblog is uninstalled

Actual result with old patch
- Error: Unable to uninstall the Database Logging module because the Lightning module is installed.

Actual result with the new patch
- dblog is uninstalled

**Comment by sylus** [comment] 2017-04-10 14:09
Yeah I am having this problem as well, no the latest lightning 2.1.0. I am unfortunately unable to disable lightning_search.

**Comment by balsama** [comment] 2017-04-18 13:39
@sylus this issue was fixed in the core patch. Can you open another issue with your steps to reproduce please? Lightning Search might be a special case. Thanks.

**Closed by balsama** 2017-04-18 13:39 UTC

**Comment by sylus** [comment] 2017-04-18 13:51
No problem! :)
