### ISSUE TITLE
Panels bandaid patch breaking save after previewing blocks with Panelizer

### ISSUE THREAD

**Issue by mortona42** [acquia/lightning#135] opened 2016-07-22 00:18 UTC
Steps to reproduce:
1. Add new Landing page
2. Add content via IPE
3. Click save > Save as custom

The save icon keeps spinning and never saves the page.

**Comment by mortenson** [comment] 2016-08-04 23:01
Don't mean to hijack the issue - but I've debugged this for a bit and have narrowed the issue down:

Easiest replication steps:

1. Use IPE on any Panelized Node
1. Click "Manage Content" > "Forms" > "Search Form"
1. Click "Toggle Preview", then "Add"
1. Save as Custom or Default
1. See 500 error in the console

The minimum environment I could get to replicate this was:

1. Install the dev release of Panels and Panelizer, enable Panelizer, and Panelize a Content Type
1. Apply https://www.drupal.org/files/issues/bandaid.patch to Panels and rebuild cache
1. Follow replication steps above

Further debugging let me see that at the point of IPE saving, the Panels Display Variant ID was different than what was being edited, which means the bandaid code is probably receiving the wrong context from somewhere.

**Comment by mortenson** [comment] 2016-08-05 01:33
I'm thinking of ways to fix this so that the Panelizer maintainers would actually commit it (rather than using bandaid-2.patch or something) - Looking back at https://www.drupal.org/node/2701433 - would a more permanent fix be using private tempstore in IPE?

The only reason IPE shares tempstore between users is that I had ambition about having Google docs-style editing between multiple users, but there's no plans to actually add that.

It's worth noting that if we moved to private tempstore, the Lightning test at https://github.com/acquia/lightning/blob/8.x-1.x/tests/features/layout/panelizer.feature#L42 would still fail, as if two Nodes are using the same default and you start editing one, there's no way for Panelizer to really know that you're intended on saving it as a custom display. This seems like expected behavior to me, and wouldn't be too jarring for users already on the bandaid. It sounds like the main issue was that one user's work leaking into another user's work, which private tempstore should fix.

Thoughts?

**Comment by balsama** [comment] 2016-08-05 11:56
Thanks for reviving this, Sam.

We wrote that test you linked to after a specific complaint on a PS project (cc @danepowell). I think it's a fairly common scenario (especially for projects that have a big "data entry" phase) and that we'd likely get more issues reported if we reintroduced it.

It sounds like that test would only fail because it's the same user though. Is that correct? If that's the case, then I imagine we could rewrite the test and users could avoid the problem by using best practice (i.e. not using the same account).

**Comment by mortenson** [comment] 2016-08-05 14:36
> It sounds like that test would only fail because it's the same user though. Is that correct?

Yes, and if you re-wrote it to have a different user login when viewing `/layout2`, it would pass before/after the tempstore change (if we want to go that route).

**Comment by balsama** [comment] 2016-08-05 15:04
++ to fixing this in a way that is more likely to actually get committed/private tempstore.

I suspect people will come across the issue where two users are logged in with the same account. No matter how much we encourage users not to, we all know that tons of people just use "admin" or "editor" accounts. But I guess that's an acceptable tradeoff... and really would be "works as designed".

**Comment by mortenson** [comment] 2016-08-05 19:34
Users who won't like this change are ones that are used to editing multiple unsaved Landing Pages (that were previously using the default) at once, but with Workbench Moderation they can just put a Landing Page into draft, make a change, save as custom, and go about their day.

I'm working on the Panels patch for this now and should have a Lightning PR in soon.

**Comment by mortenson** [comment] 2016-08-22 18:05
Using PrivateTempStore in Panels IPE causes issues with other Lightning patches and tests, so I'm going to hold off on the PR for now but leave this issue open as there is still a Lightning bug related to the bandaid patch.

Some thoughts - So from what I understand, the bandaid patch addressed two problems Lightning users saw:

1. When two users are using IPE on new Landing Pages, their work would overlap and make concurrent Landing Page creation impossible.
1. If a Panelized Entity allowed custom (per-Entity) displays, Panelizer would still use the default TempStore key on new Landing Pages. This made editing two new Landing Pages with IPE as one user impossible.

The issue I opened for Panels (https://www.drupal.org/node/2779813 addresses the first problem, but will not change how Panelizer chooses the TempStore key when using IPE.

If I've missed any bugs that the bandaid patch addressed let me know and I'll update this comment.

**Comment by mortenson** [comment] 2016-10-05 15:10
It's worth noting that the bandaid patch has moved to a new patch in [this commit](https://github.com/acquia/lightning/commit/30a5c1d9cfde15191036ee186772a788cbc46bc0#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R66), which has the same issues as the bandaid. My team was previously ignoring the bandaid patch for this reason but now we'll start ignoring the new patch.

**Comment by mortenson** [comment] 2017-02-28 03:48
@mortona42 Are you still seeing this issue with Lightning? I just tried to reproduce it, and couldn't! Which is awesome 👍

**Comment by mortona42** [comment] 2017-03-01 01:03
Sorry, I haven't touched it in a while.

**Comment by balsama** [comment] 2017-05-24 14:40
Likely fixed elsewhere. Thanks!

**Closed by balsama** 2017-05-24 14:40 UTC
