### ISSUE TITLE
Crossgrade to core Media module

### ISSUE THREAD

**Issue by balsama** [acquia/lightning#489] opened 2017-10-20 01:27 UTC
The latest branch can be found here:
https://github.com/acquia/lightning/tree/core-media

Tests there are passing, including the update path. But when I tried to implement the update path in a real codebase, I came across some errors. Generally, something about the media library field already existing.

I've created a Lightning Project branch with the most simple update here:
https://github.com/balsama/lightning-project/tree/media-update

I see warnings in the update hooks there, but no errors. The behat tests ultimately fail in the "Bulk uploading media assets" feature. Tests here (expand the `if [ $VERSION = "HEAD" ];` step):
https://travis-ci.org/balsama/lightning-project/jobs/290261015

**Comment by balsama** [comment] 2017-10-20 13:08
Looks like the update is complaining about missing the media_entity_document and media_entity_image modules. I think both of those have been moved to core so it would make sense that we removed them. But it also makes sense that the update path would need them. As far as why this didn't fail in our tests within the Lightning repo... I suspect it's because the rsync called in phing push doesn't actually delete those dependencies from the codebase.

Testing now

**Comment by balsama** [comment] 2017-10-20 18:48
Ok. I've worked through this and I think everything is fairly trivial to fix 🎉. So I think we'll actually be OK for 25 Oct release. My test case involved a sub-profile of Lightning built from exported config that defined a new media entity and a Media reference field on Page.

Acceptance:
* No errors in Update path
* Content types, fields, and content are all migrated properly
* Config export and new install has all content types and fields as expected.

## Problem 1
* Media Entity Image and Media Entity Document are needed for the update path.
* The 1.2.0 and 1.1.0 releases of each respectively purposely conflict with the 2.x branch of Media Entity.
* Composer downgrades to the 1.1.0 and 1.0.0 releases when you update your codebase.
* The update path actually appears to run fine either way.

**Note**: This problem went undetected because the rsync used in Lightning dev didn't actually delete them from the running codebase.
**Resolution**: Add both modules back into the composer require section for at least one release.

## Problem 2
* Video embed field reports that 8.x-2.0-alpha1 is unsupported.
* This is possibly just because the maintainer has it hidden on the project page.

**Resolution**: talk to the maintainer and see if he mark it as supported.

## Problem 3
* Media Entity module remains installed after update.
* Config exports and subsequent site installs fail because contrib media entity (correctly) conflicts with other installed extensions

**Resolution**: Uninstall contrib Media Entity Module at end of update.

## Problem 4
* Entity Browser 8.x-2.0-alpha1 reports that it is incompatible with the installed version of Media Entity
* This is fixed by uninstalling the contrib Media Entity module (which the update path should do)

**Resolution**: Should be fixed as part of Problem 3.

**Comment by phenaproxima** [comment] 2017-10-21 15:27
I did some debugging to determine the causes of various exceptions during the update process, when building from Lightning Project with a sub-profile.

Here, for our reference, are my notes from that debugging session:

On the first composer update, drupal/core is not removed and re-patched. This ends up causing the "Field already exists" exception -- because the media types packaged with Media are being created. With the proper patch applied, they are not. Fixing this should also get rid of the routing exception, since nothing is being deleted either.

Media Entity should not be defining revision metadata keys in its entity type definition. It should just do exactly what 1.x did. This should get rid of the database exceptions.

**Comment by phenaproxima** [comment] 2017-10-24 12:51
Problem 1 is blocked by two contrib issues. And no, we cannot patch around them:

https://www.drupal.org/node/2916854
https://www.drupal.org/node/2916852

**Comment by phenaproxima** [comment] 2017-10-24 12:54
With regard to Problem 2, we can talk to Sam152 about it, but I suspect he will be hesitant to mark VEF 2.x as supported until the core crossgrade path is at least somewhat ready. Which is understandable. But, that's a theory. Let's see what he says.

**Comment by phenaproxima** [comment] 2017-10-24 12:55
Problem 3: I don't know if Media Entity can, or should, uninstall itself after the update. Not sure if it would break anything. I'm not even sure if Media Entity *can* uninstall itself. But it's worth a shot.

**Comment by phenaproxima** [comment] 2017-10-24 13:26
With regard to this:

> Media Entity should not be defining revision metadata keys in its entity type definition. It should just do exactly what 1.x did. This should get rid of the database exceptions.

This has been reported by someone else, and I have filed a patch: https://www.drupal.org/node/2918172#comment-12312963

**Comment by phenaproxima** [comment] 2017-10-24 13:27
One of our blocking contrib issues, preventing Media Entity Image from being present in a code base alongside Media Entity 2.x, has landed: https://www.drupal.org/node/2916854

**Comment by balsama** [comment] 2017-10-24 13:30
Using the 1.1.0 and 1.0.0 versions of Media Entity Image and Document (which don't conflict with Media Entity 2.x)  actually doesn't seem to cause any problems.

See this test project: https://github.com/balsama/media-update
And the alpha tag: https://github.com/acquia/lightning/releases/tag/2.2.1-alpha1

**Comment by phenaproxima** [comment] 2017-10-24 13:31
Fair. It mostly has to do with our (the Media Initiative's) ability to test the update path.

**Comment by balsama** [comment] 2017-10-24 13:52
Re: https://www.drupal.org/node/2918172#comment-12312963

None of our tests are failing. Should we write a failing test for it and bring it in? Or is it possible that it doesn't cause a problem?

Let's use https://github.com/balsama/media-update in addition to the Lightning repo as our source of truth for testing.

**Comment by phenaproxima** [comment] 2017-10-24 13:54
I don't think we specifically need to do anything about that issue. seanB, or (hopefully) the issue author will manually test and report back.

**Comment by balsama** [comment] 2017-10-24 13:56
Update:
**Problem 1**:
Seems to be a non issue if we just let composer downgrade to the previous releases of each.

**Problem 2**:
Open. Could be solved in release notes

**Problem 3**:
Patch applied and tests passing

**Problem 4**:
Solved by Problem 3

**Media Entity revision metadata**:
Apparently not an issue

**Comment by phenaproxima** [comment] 2017-10-24 13:58
I was encountering the revision metadata stuff while testing the update path under a Lightning Project build. It was consistently happening for me. I have reason to believe this is a critical bug with the update path -- I think we just weren't reproducing it due to the circumstances of our build.

**Comment by balsama** [comment] 2017-10-24 13:58
Left to do:

* Get video embed maintainer to mark release as supported, or add it to our known issues section.
* Get a tag on Media Entity 2.x, or a patch that updates from 1.x to 2.x
* Troubleshoot and fix the alpha1 update path which is failing for some reason here https://travis-ci.org/acquia/lightning/builds/291721171

**Comment by phenaproxima** [comment] 2017-10-24 14:25
The contrib issue against Media Entity Document landed as well: https://www.drupal.org/node/2916852

**Comment by phenaproxima** [comment] 2017-10-24 15:59
Problems 1, 3 and 4 should be fixed now in my fork of the core-media branch.

**Comment by balsama** [comment] 2017-10-25 11:45
This is all merged and tests are passing in [Lightning](https://travis-ci.org/acquia/lightning/builds/292397502), [Lightning Project](https://travis-ci.org/acquia/lightning-project/builds/292420281), and the [Media Update](https://travis-ci.org/balsama/media-update/builds/292269402) project.

A couple of notes.

1. A cache rebuild is definitely needed after you update your code, before you run the database updates. See [here](https://travis-ci.org/balsama/media-update/jobs/292412221#L1188) and [here](https://travis-ci.org/balsama/media-update/jobs/292412223#L1196). I've added that step in our release notes.
2. Drupal Console seems to work just as reliably for the updates as Drush, as Lightning Project demonstrates [here](https://travis-ci.org/balsama/lightning-project/builds/292415545).
3. I've added some additional notes to our [update steps](https://github.com/acquia/lightning/blob/8.x-2.x/UPDATE.md#special-instructions-for-media-entity-migration) that explain the cache rebuild and ensuring all the patches are applied.

All that said, I think we're good to go. But feedback is welcome on the above.

**Closed** 2017-10-30 17:50 UTC
