### ISSUE TITLE
Add webflo/drupal-core-strict

### ISSUE THREAD

**Issue by naveenvalecha** [acquia/lightning#391] opened 2017-06-21 09:13 UTC
Add [webflo/drupal-core-strict](https://github.com/webflo/drupal-core-strict)

it is a virtual package, that causes you to get exactly the versions of Drupal core's dependencies as they are specified in Drupal core's composer.lock file

Referencing PR https://github.com/acquia/reservoir/pull/6

**Comment by balsama** [comment] 2017-06-21 13:00
I'm against this as it goes against the best practices of Composer. There is a reason dependencies' lock files don't bubble up to the parent. Let's let dependencies negotiate versions as Composer intended, not artificially constrain options.

**Comment by mdonadio** [comment] 2017-06-21 13:21
The problem is that if someone runs a `composer update`, they may get untested dependencies. There are some known issues with newer versions of Symfony and Twig, which is why core doesn't use the latest versions.

**Comment by balsama** [comment] 2017-06-21 13:24
Thanks for the clarification. I wasn't aware of that issue with core. Do you have a link by chance?

Either way, I'd rather file a patch against core (if it doesn't already exist) and temporarily constrain those Twig and Symfony dependencies in our own composer.json file if needed.

**Comment by naveenvalecha** [comment] 2017-06-22 19:50
I did a quick search in Drupal issue queue and here's the handy link for the d.o issue https://www.drupal.org/node/2887000
However, this issue is only taking care of the Symfony packages. There could be other packages which could also create issues.

**Comment by balsama** [comment] 2017-06-28 21:22
Ok - thanks for that issue, @naveenvalecha. Looks like that core issue now has a proper patch to composer.json, which would get considered by a requiring package like Lightning.

Also note that our CI tool builds Lightning from a scaffold project daily and runs Lightning's tests against the following:
* The highest negotiated dependency resolution against last stable Lightning release (normal `composer update`)
* The lowest negotiated dependency resolution against last stable Lightning release (`composer update` with `prefer --lowest)
* HEAD of the 8.x-2.x Lightning branch with highest negotiated dependency resolution
* A sub-profile of Lightning

So we should catch any dependency issues within 24 hours of a dependency updating. I'm going to close this - but thanks for bringing it up. It started many interesting discussions even though 'm still against it. Thanks!

**Closed by balsama** 2017-06-28 21:22 UTC
