### ISSUE TITLE
Cannot select existing images in the image browser

### ISSUE THREAD

**Issue by mortenson** [acquia/lightning#506] opened 2017-11-01 16:30 UTC
When Lightning moved to use core Media, the widget for selecting existing Images was removed from the Image Browser Entity Browser: https://github.com/acquia/lightning/commit/62c94fe0dea892ad529d0968e25a6fd4ed2cb604#diff-b57042741ec43be7603aef451c28c4fdL22

As a result, any new Lightning user who uses the Image Browser Entity Browser on an Image field will only be able to upload new Images.

This appears to be a bug, as the View display for this widget ("Image Browser" in the "Media" view) still exists.

**Comment by balsama** [comment] 2017-11-07 18:53
I'm having trouble reproducing this.

Here is a basic page content type with two additional fields:
1. Media reference set to allow only images
1. Image reference fiels

http://lightningnightlytthkk6h3hg.devcloud.acquia-sites.com/node/add/page (admin/admin)

Both fields still have a library tab on their EB. Assigning to @phenaproxima to see if I missed something obvious, but feel free to clarify @mortenson.

**Comment by mortenson** [comment] 2017-11-07 19:24
@balsama I can't reproduce the problem on your test site either, here's my dig:

Here you can see that the only Entity Browser widget for the image_browser Entity Browser is "Upload": https://github.com/acquia/lightning/blob/8.x-2.x/modules/lightning_features/lightning_media/modules/lightning_media_image/config/install/entity_browser.browser.image_browser.yml#L18

But on your test site, a "Library" widget is present: http://lightningnightlytthkk6h3hg.devcloud.acquia-sites.com/admin/config/content/entity_browser/image_browser/widgets?js=nojs

There is no configuration for the "Library" widget in the Lightning codebase, so I was confused to see it in your test site. After some digging I found this, which adds the widget in lightning_media when the "media" view is created:

https://github.com/acquia/lightning/blob/62c94fe0dea892ad529d0968e25a6fd4ed2cb604/modules/lightning_features/lightning_media/modules/lightning_media_image/lightning_media_image.module#L33

The problem with this code is that the Media module may have been enabled _before_ Lightning Media, which means this part of the hook would never be run and the widget would never be added. To resolve this issue, I think that Lightning Media would also need to check for the presence of the "media" View on install.

**Comment by balsama** [comment] 2017-11-07 19:34
Ah, yes. It seems that Lightning Media always ends up getting installed after Media in our setup, but this isn't guaranteed.

We do this in several other places. Thanks for helping get to the bottom of this.

**Comment by mortenson** [comment] 2017-11-08 15:32
@phenaproxima No, we use on Lightning Media in Demo Framework.

**Comment by phenaproxima** [comment] 2017-11-08 15:37
@mortenson Okay, that's strange...here's the thing.

The hook you mentioned acts on the media view at site install time (drupal_installation_attempted()). Module installation order shouldn't be making any different, because the media view is optional config, which is installed all at once, after all modules have been installed. So the hook, as written, *should* work as intended during a normal site install. I guess we must be missing something, but I'm not sure what that could be...

**Comment by mortenson** [comment] 2017-11-08 15:43
@phenaproxima If I installed Views and Media, then I installed Lightning Media Image, the logic in `lightning_media_image_view_insert` would not be run (the View entity was already inserted). A sub-profile could have Views and Media installed before Lightning Media Image due to other dependencies, the install order isn't guaranteed.

**Comment by phenaproxima** [comment] 2017-11-08 15:45
> A sub-profile could have Views and Media installed before Lightning Media Image due to other dependencies, the install order isn't guaranteed.

@mortenson That is correct, but during installation, the install order doesn't matter if you're going to be altering optional config (which includes the media view). Optional config is always installed in a single batch after ALL modules are installed.

**Comment by mortenson** [comment] 2017-11-08 15:58
@phenaproxima You can replicate our issue by installing Demo Framework (https://github.com/acquia/df), logging in, and visiting `/node/add/article`. The "Image" field there only allows uploads as of the recent Lightning update.

**Comment by phenaproxima** [comment] 2017-11-08 16:37
I haven't been able to reproduce this with a stock DF install, on my localhost.

![506-uh-oh](https://user-images.githubusercontent.com/4504530/32561050-3c4edbae-c479-11e7-9bf4-8f0274b57c2c.png)

**Comment by mortenson** [comment] 2017-11-08 18:30
@phenaproxima My team just tried out building acquia/df from dev and we all saw the same issue, how were you building DF locally? The latest release does not use the newest release of Lightning, you can only see this issue by building dev.

**Comment by mortenson** [comment] 2017-11-08 18:30
@phenaproxima My team just tried out building acquia/df from dev and we all saw the same issue, how were you building DF locally? The latest release does not use the newest release of Lightning, you can only see this issue by building dev.

**Comment by DevinCarlson** [comment] 2017-11-08 18:35
With the rewrite removed, you can see the failing test at: https://travis-ci.org/DevinCarlson/df/jobs/299225557#L2606

**Comment by DevinCarlson** [comment] 2017-11-08 18:36
With the rewrite removed, you can see the failing test at: https://travis-ci.org/DevinCarlson/df/jobs/299225557#L2606

**Comment by balsama** [comment] 2017-11-08 18:55
I was able to reproduce this. To be crystal clear:

1. git clone git@github.com:acquia/df.git
2. cd df && composer install
3. drush si df

then

1. visit /node/add/article
2. Click on "Image" -> "Select Images"
3. Note no Library tab

**Comment by phenaproxima** [comment] 2017-11-08 20:39
I am reproducing this now -- my problem was that I had been on the last stable release (I used composer create-project), not HEAD.

I'll see what I can do.

**Comment by phenaproxima** [comment] 2017-11-09 14:30
Messrs. @mortenson and @balsama, I believe I have this fully traced.

I'd describe the problem as a confluence of assumptions, made by both Lightning and DF, which are breaking each other. However, Lightning is in this case hewing more closely to core's built-in behavior, so personally I think the fix needs to happen in DF.

df_tools_media is using the config_rewrite module to rewrite the media view (views.view.media). In Lightning pre-2.2.1, this view was default config shipped with Media Entity, which means it was installed at the same time Media Entity was. In core, the view is _optional_ config. Optional config is handled differently than default config -- during a site install, all the optional config is installed in a single batch _at the end of the process_. It is NOT installed along with the module that shipped it.

This change meant that Lightning had to implement hook_view_insert() to alter the views, since we could not rely on the view existing in hook_install(). So that is exactly what we did.

So, along comes df_tools_media and its rewritten config. What ends up happening is that, just before df_tools_media is installed, config_rewrite springs into action and creates a config object, called views.view.media, from the stuff in df_tools_media/config/rewrite/views.view.media.yml. THEN, df_tools_media is installed, and df_tools_media_install() is able to load the media view and modify it, because the config upon which the view entity is based is already there (thanks to config_rewrite). Then it saves the view.

But remember -- *the view already existed*, because config_rewrite put it there, albeit using a lower-level system. So when df_tools_media_install() calls $view->save(), Lightning's hook is never fired, because it is only reacting to a newly created-view, not a pre-existing view (which is completely intentional -- we do not want to modify existing views, since that could blow away or modify expected behavior). Because Lightning's hook isn't fired, the image browser is never updated, and the tab never appears.

And that's why DF has this problem, but vanilla Lightning does not.

My feeling is that DF should refactor so that it reacts when the view is inserted, rather than assuming it will be there at install time. It would probably need to run *after* Lightning's hooks, though, so that'll involve terrible things like hook_module_implements_alter(). (This, by the way, is exactly why entity hooks need to become event subscribers with explicit, overridable weighting.) If another, easier solution could be done in Lightning, I'm open to that...but as far as I can tell, this is the only real fix.

Thoughts?

**Comment by mortenson** [comment] 2017-11-09 19:26
@phenaproxima That makes sense, it appears that Config Rewrite does have a bug here that needs to be addressed. There's already an open issue for this here: https://www.drupal.org/node/2903629

We're working on a more up to date patch for that issue, but we have older logic in Demo Framework that assumes the Media View will be around at install time. The Media View has been moved to config/optional in core, but was not optional in contrib (see http://cgit.drupalcode.org/media_entity/tree/config/install). As a result, the upgrade path from contrib to core has led to a kind of cascading problem for us, I wouldn't call it a regression but we have to re-think how we do things now.

**Comment by phenaproxima** [comment] 2017-11-09 22:53
@mortenson Yeah, I know. I'm sorry about that :(

It doesn't seem like there's much else Lightning can do here, so I'm closing this. Feel free to re-open if we can continue to be helpful.

**Closed by phenaproxima** 2017-11-09 22:53 UTC
