### ISSUE TITLE
new subprofile system is broken

### ISSUE THREAD

**Issue by dgpalmer** [acquia/lightning#355] opened 2017-04-27 22:40 UTC
Hi,

i was using lightning.extend.yml sucessfully for many months. with the latest drupal core and lightning, a subprofile is required. unfortunately, i am having major issues with this. i have tried to follow the instructions on https://docs.acquia.com/lightning/subprofile with no luck. I am experiencing issues with configuration dependencies.

e.g: 
```
$ dr @asf8.dd si asf --account-name=admin --account-pass=awesomepassword

exception 'Drupal\Core\Config\UnmetDependenciesException' with message 'Configuration objects provided by <em class="placeholder">umg_brand</em> have unmet [error]
dependencies: <em class="placeholder">core.entity_form_display.node.artist.default (path, workbench_moderation)</em>'
```

 I tried moving my module dependencies to the install hook as recommended in the docs, but now for instance, the bartik theme is failing to install.

```
$ dr @asf8.dd si asf --account-name=admin --account-pass=awesomepassword

exception 'Drupal\Core\Config\UnmetDependenciesException' with message 'Configuration objects provided by <em class="placeholder">lightning</em> have unmet [error]
dependencies: <em class="placeholder">block.block.bartik_account_menu (block)</em>' in
```

How can I move past this? I never had this problem with the lightning.extend.yml file.

My info.yml looks like this:
```name: 'Artist Site Factory'
type: profile
version: 8.x-dev
description: 'Drupal 8 Artist Site Factory Distribution based on Acquia Lightning'
core: '8.x'
dependencies:

themes:
  - bartik
  - seven

base profile:
  name: lightning
  excluded_dependencies:
    - lightning_media_instagram
    - lightning_layout
    - lightning_landing_page
```
my .install looks like
```<?php

/**
 * @file
 * Install, update and uninstall hooks for the Artist Site Factory subprofile.
 */

/**
 * Implements hook_install().
 */
function asf_install() {
  //  module dependencies
  $modules = [
    'field_group',
    'umg_brand',
    'asf_events',
    'asf_photos'
    'asf_twitter',
    'asf_videos'
  ];
  foreach ($modules as $module) {
    \Drupal::service('module_installer')->install([$module]);
  }
}
```
What do I need to do?

**Comment by phenaproxima** [comment] 2017-04-27 22:44
From your bug report, it's not entirely clear what's going wrong, but one thing does leap out at me -- there is no need to install your modules in hook_install(). That's what your subprofile should do. So I would recommend removing asf_install() entirely, then modify the dependencies in your info.yml to look like this:

```
dependencies:
  - field_group
  - umg_brand
  - asf_events
  - asf_photos
  - asf_twitter
  - asf_videos
```
I can't promise what sort of effect this will have, but it's worth a try.

**Comment by dgpalmer** [comment] 2017-04-27 22:45
Thanks for the quick response Adam, that's what I originally had from the drupal lightning:subprofile generation but that produced the first error about the unmet configurations.

**Comment by dgpalmer** [comment] 2017-04-27 22:52
I was able to get past the Configuration objects provided by <em class="placeholder">umg_brand</em> have unmet [error]
dependencies: <em class="placeholder">core.entity_form_display.node.artist.default (path, workbench_moderation)</em>' by adding path & workbench moderation to my dependencies as well, but now I get this:

```'Configuration objects provided by <em class="placeholder">umg_brand</em> have unmet [error]
dependencies: <em class="placeholder">core.entity_view_display.node.artist.teaser (core.entity_view_mode.node.teaser)</em>' ```

Seems like its trying to install my modules before core & lightning have been installed.

**Comment by dgpalmer** [comment] 2017-04-27 23:17
I was able to get past some of these errors by adding dependencies to "node", "taxonomy", "menu", etc. Why should I have to define all these core modules as dependencies? This doesn't seem right at all and I didn't have to before.

**Comment by balsama** [comment] 2017-04-28 00:11
I think it's the empty `dependencies` key in the original info file you posted that's causing problems. Try removing that or changing it to an empty array: `{}`.

**Comment by dgpalmer** [comment] 2017-04-28 18:36
@balsama That didn't work, I still got the same error as before. I also just tried this on another lighting project I had and I am experiencing the same problem. This other site has a module with a block configuration for a block enabled in the sidebar of the bartik theme. When I try to install the subprofile, it says there is an unmet configuration dependency (bartik) and fails to install.

Both these lightning projects had no configuration dependency issues with the lightning.extend.yml and the new profile info.yml's have everything the lightning.extend.yml did.

**Comment by balsama** [comment] 2017-05-01 13:06
I think we're missing something here. The empty `dependencies` key would definitely cause the install to fail. I was also able to install successfully using the info file from the original issue summary (after fixing the dependencies key).

Can you share some more information? Your composer.json? Is your codebase public so we can take a look?

**Comment by balsama** [comment] 2017-05-09 12:21
Hi Donovan. Any other information on this? Can we help troubleshoot in any way?

**Comment by dgpalmer** [comment] 2017-05-10 01:28
Hi Adam, sorry was pulled into another project last week...

Here is the composer.json for one of my projects:

```{
    "name": "umg/asf8",
    "description": "Project template for Drupal 8 sites built with BLT.",
    "type": "project",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "repositories": {
        "sfmc-php": {
            "type": "vcs",
            "url": "git@bitbucket.org:interscoperecords/sfmc-php.git"
        },
        "sfmc": {
            "type": "vcs",
            "url": "git@bitbucket.org:interscoperecords/sfmc.git"
        },
        "asf_twitter": {
            "type": "vcs",
            "url": "git@bitbucket.org:interscoperecords/asf_twitter.git"
        },
        "asf_events": {
            "type": "vcs",
            "url": "git@bitbucket.org:interscoperecords/asf_events.git"
        },
        "asf_photos": {
            "type": "vcs",
            "url": "git@bitbucket.org:interscoperecords/asf_photos.git"
        },
        "asf_videos": {
            "type": "vcs",
            "url": "git@bitbucket.org:interscoperecords/asf_videos.git"
        },
        "umg_brand": {
            "type": "vcs",
            "url": "git@bitbucket.org:interscoperecords/umg_brand.git"
        },
        "drupal": {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    },
    "require": {
        "acquia/blt": "^8.3",
        "umg/sfmc-php": "dev-master",
        "cweagans/composer-patches": "^1.6.0",
        "drupal/sfmc": "dev-master",
        "drupal/acsf": "^1.37.0",
        "drupal/acquia_contenthub": "^1.9",
        "acquia/lightning": "~2.1.0",
        "drupal/field_group": "1.0.0-rc6",
        "drupal/umg_brand": "dev-master",
        "drupal/asf_events": "dev-8.x-1.x",
        "drupal/asf_photos": "dev-8.x-1.x",
        "drupal/asf_videos": "dev-8.x-1.x",
        "drupal/asf_twitter": "dev-master",
        "drupal/search_api": "1.0",
        "drupal/search_api_solr": "1.0.0-beta2",
        "drush/drush": "^8.1.8",
        "drupal/address": "1.0.0-rc3"
    },
    "require-dev": {
        "drupal/devel": "^1.0.0-alpha1",
        "drupal/coder": "~8.2",
        "jakoch/phantomjs-installer": "^2.1.1-p07",
        "drupal/console": "^1.0.0-rc17"
    },
    "extra": {
        "blt": {
            "update": true
        },
        "enable-patching": true,
        "installer-paths": {
            "docroot/core": ["type:drupal-core"],
            "docroot/modules/contrib/{$name}": ["type:drupal-module"],
            "docroot/modules/custom/{$name}": ["type:drupal-custom-module"],
            "docroot/profiles/contrib/{$name}": ["type:drupal-profile"],
            "docroot/profiles/custom/{$name}": ["type:drupal-custom-profile"],
            "docroot/themes/contrib/{$name}": ["type:drupal-theme"],
            "docroot/themes/custom/{$name}": ["type:drupal-custom-theme"],
            "docroot/libraries/{$name}": ["type:drupal-library"],
            "drush/contrib/{$name}": ["type:drupal-drush"]
        },
        "patches": [],
        "merge-plugin": {
            "require": [
                "vendor/acquia/blt/composer.required.json",
                "vendor/acquia/blt/composer.suggested.json"
            ],
            "include": [
                "blt/composer.overrides.json"
            ],
            "merge-extra": true,
            "merge-extra-deep": true,
            "merge-scripts": true,
            "replace": true
        }
    }
}
```

Here is it's profile's info file

```
name: 'Artist Site Factory'
type: profile
version: 8.x-dev
description: 'Drupal 8 Artist Site Factory Distribution based on Acquia Lightning'
core: '8.x'
base profile:
  name: lightning
  excluded_dependencies:
    - lightning_media_instagram
    - lightning_layout
    - lightning_landing_page

dependencies:
  - address
  - ctools
  - rest
  - acquia_contenthub
  - path
  - workbench_moderation
  - field_group
  - node
  - taxonomy
  - datetime
  - lightning_core
  - lightning_media
  - lightning_media_twitter
  - video_embed_field
  - umg_brand
  - asf_events
  - asf_photos
  - asf_twitter
  - asf_videos

themes:
  - bartik
  - seven
```

Here is my other project where I experienced similar issues, mainly with the Bartik theme and a block my module was trying to place in it:

```
{
    "name": "umg/umgch",
    "license": "proprietary",
    "type": "project",
    "description": "A Drupal 8 project for UMGs content hub.",
    "repositories": {
        "0": {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        },
        "drupal": {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    },
    "require": {
        "acquia/blt": "8.8.1",
        "cweagans/composer-patches": "^1.6.0",
        "drupal/acsf": "^1.37.0",
        "drupal/core": "~8",
        "acquia/lightning": "^2",
        "drupal/field_group": "1.0.0-rc6",
        "drupal/migrate_plus": "3.0.0-beta1",
        "drupal/migrate_tools": "3.0.0-beta1",
        "google/apiclient": "^2.0",
        "drupal/acquia_contenthub": "^1.9",
        "guzzlehttp/oauth-subscriber": "0.3.0",
        "abraham/twitteroauth": "^0.7.0",
        "sainsburys/guzzle-oauth2-plugin": "3.0.1",
        "drupal/paragraphs": "1.1.0",
        "drupal/seckit": "1.0.0-alpha2",
        "drupal/field_collection": "1.0.0-alpha1",
        "drupal/address": "1.0.0-rc3",
        "drupal/restui": "1.13.0"
    },
    "require-dev": {
        "squizlabs/php_codesniffer": "2.*",
        "drupal/devel": "1.0.0-alpha1",
        "drupal/console": "^1.0.0-rc17"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "installer-paths": {
            "docroot/core": [
                "type:drupal-core"
            ],
            "docroot/modules/contrib/{$name}": [
                "type:drupal-module"
            ],
            "docroot/modules/custom/{$name}": [
                "type:drupal-custom-module"
            ],
            "docroot/profiles/contrib/{$name}": [
                "type:drupal-profile"
            ],
            "docroot/profiles/custom/{$name}": [
                "type:drupal-custom-profile"
            ],
            "docroot/themes/contrib/{$name}": [
                "type:drupal-theme"
            ],
            "docroot/themes/custom/{$name}": [
                "type:drupal-custom-theme"
            ],
            "docroot/libraries/{$name}": [
                "type:drupal-library"
            ],
            "drush/contrib/{$name}": [
                "type:drupal-drush"
            ]
        },
        "patches": {
            "drupal/migrate_tools": {
                "Use the core plugin manager": "https://www.drupal.org/files/issues/use_the_core_plugin-2795447-3.patch"
            },
            "drupal/core": [],
            "drupal/migrate_plus": [],
            "drupal/acquia_contenthub": []
        },
        "blt": {
            "update": true
        },
        "drupal-scaffold": {
            "initial": {
                "sites/default/default.services.yml": "sites/default/services.yml",
                "sites/default/default.settings.php": "sites/default/settings.php"
            }
        },
        "enable-patching": true,
        "merge-plugin": {
            "require": [
                "vendor/acquia/blt/composer.required.json",
                "vendor/acquia/blt/composer.suggested.json"
            ],
            "include": [
                "blt/composer.overrides.json"
            ],
            "merge-extra": true,
            "merge-extra-deep": true,
            "merge-scripts": true,
            "replace": true
        }
    }
}
```

Here is it's profiles info.yml

```
name: 'UMG Middleware'
type: profile
version: 8.x-dev
description: 'Drupal 8 UMG Middleware Distribution for Content Hub based on Acquia Lightning'
core: '8.x'
dependencies:
# core
  - block
  - serialization
  - node
  - taxonomy
  - path
  - datetime
# contrib
  - address
  - ctools
  - migrate_plus
  - migrate_tools
  - workbench_moderation
  - field_group
  - lightning_core
  - lightning_media
  - lightning_media_twitter
  - video_embed_field
# umgmw
themes:
  - bartik
  - seven
base profile:
  name: lightning
  excluded_dependencies:
    - lightning_layout
    - lightning_landing_page
```

Here is it's .install since I had to go that route due to the bartik theme issue:

```
<?php

/**
 * @file
 * Install, update and uninstall hooks for the UMG Middleware subprofile.
 */

/**
 * Implements hook_install().
 */
function umgmw_install() {
  // Add code here perform additional site information tasks, generate sample
  // content, etc.
	$modules = [
  	'umg_brand',
  	'events',
  	'migrate_ae_brand',
  	'migrate_bit',
  	'migrate_plus_client',
  	'migrate_instagram',
  	'migrate_twitter',
  	'migrate_youtube',
	];
	foreach ($modules as $module) {
			\Drupal::service('module_installer')->install([$module]);
	}
}
```

**Comment by balsama** [comment] 2017-05-10 01:52
Thanks. I'm going to recreate this as much as possible and see if I come across anything.

In the meantime, what version of BLT do you have and what's in the `vendor/acquia/blt/composer.required.json` and `vendor/acquia/blt/composer.suggested.json` files?

**Comment by dgpalmer** [comment] 2017-05-10 03:06
Version 8.8.3 of BLT.

vendor/acquia/blt/composer.required.json

```
{
  "repositories": {
    "drupal": {
      "type": "composer",
      "url": "https://packages.drupal.org/8"
    }
  },
  "require": {
    "drupal/core": "^8.0",
    "drupal/features": "^3.0.0",
    "drupal/config_split": "^1.0.0-beta4",
    "drupal/devel": "^1.0.0-alpha1"
  },
  "require-dev": {
    "cweagans/composer-patches": "^1.6.0",
    "behat/behat": "^3.1",
    "behat/mink": "~1.7",
    "behat/mink-selenium2-driver": "^1.3.1",
    "bex/behat-screenshot": "^1.2",
    "drupal/drupal-extension": "^3.2",
    "drupal-composer/drupal-scaffold": "^2.1.0",
    "jarnaiz/behat-junit-formatter": "^1.3.2",
    "se/selenium-server-standalone": "^2.53",
    "jakoch/phantomjs-installer":   "2.1.1-p07"
  },
  "autoload-dev": {
    "psr-4": {
      "Drupal\\Tests\\PHPUnit\\": "tests/phpunit/src/"
    }
  },
  "autoload": {
    "psr-4": {
      "Acquia\\Blt\\Custom\\": "../../../blt/src/"
    }
  },
  "extra": {
    "composer-exit-on-patch-failure": true,
    "drupal-scaffold": {
      "initial": {
        "sites/default/default.services.yml": "sites/default/services.yml",
        "sites/default/default.settings.php": "sites/default/settings.php"
      },
      "excludes": [
        "sites/development.services.yml"
      ]
    },
    "enable-patching": true,
    "patches": {
      "drupal/core": {
        "Clear Twig caches on deploys": "https://www.drupal.org/files/issues/no_reliable_method-2752961-29.patch"
      }
    }
  },
  "scripts": {
    "blt-alias": "blt install-alias -Dcreate_alias=true",
    "drupal-scaffold": "DrupalComposer\\DrupalScaffold\\Plugin::scaffold",
    "nuke": [
      "rm -rf vendor composer.lock",
      "@composer clearcache",
      "@composer install"
    ],
    "install-phantomjs": [
      "rm -rf vendor/bin/phantomjs",
      "PhantomInstaller\\Installer::installPhantomJS"
    ]
  }
}
```

vendor/acquia/blt/composer.suggested.json

```
{
  "require": {
    "acquia/lightning": "^2.0.3",
    "drupal/acquia_connector": "^1.5.0",
    "drupal/cog": "^1.0.0",
    "drupal/qa_accounts": "^1.0.0-alpha1",
    "drupal/memcache": "2.x-dev",
    "drupal/seckit": "^1.0.0-alpha2",
    "drupal/security_review": "*",
    "drupal/shield": "^1.0.0"
  },
  "extra": {
    "patches": {
    }
  }
}
```

**Comment by balsama** [comment] 2017-05-10 11:43
I guess we'll have to assume that none of the stuff in those merge files is causing problems. Nothing really hints at that, but they always make me nervous. Either way, it might be nice to just triple check that you are getting 2.1.3 of Lightning and that it has the 303 version of inherited profiles patch applied.

I spun up this repo as a test environment: https://github.com/balsama/umg-test

It's based on the first composer.json file above and includes the first .profile file you posted as a subprofile. It doesn't 100% represent your build since your custom stuff is private. But it does test your profile file as a subprofile of Lightning.

I was able to install ASF and run a test on Lightning media (confirms Lightning is installed) and run a second test that asserts the active profile is ASF.

Here are the test build and test results: https://travis-ci.org/balsama/umg-test/builds/230616618

I'm not sure what this proves (other than that the sub-profile system _isn't_ utterly broken, but we already test that in our CI). It might provide a clue as to what's going wrong with your build though.

Hit me up on IRC today (balsama) if you want to schedule a screenshare.

**Comment by dgpalmer** [comment] 2017-05-10 21:32
It's relatively fine, the files I posted yesterday do *work*. I just have to define a lot of dependencies which I didn't have to do in the lightning extend,  which is why I created this issue. It just seems wrong to me that I have to declare "taxonomy" or "lightning_core" for example as a dependency, especially given that in the profile's info.yml, it says its base profile is lightning, so how does it not realize that lightning_core is a dependency? It just seems odd that I have to tell it that.

Thanks,
Donovan

**Comment by balsama** [comment] 2017-05-11 00:13
You're absolutely right. You definitely should _not_ have to declare lightning_core as a dependency in your sub-profile. I actually missed the fact that you were doing that in all this. I just removed it from the test script. Let's see what happens.

**Comment by balsama** [comment] 2017-05-11 00:44
That passed with no trouble as expected:
https://travis-ci.org/balsama/umg-test/builds/230981802

Why, exactly, were you listing lightning_core as a dependency? Is it not getting installed at all, or were you having unmet dependency exception issues?

**Comment by dgpalmer** [comment] 2017-05-11 00:54
I was getting the unmet dependency exception error. I just took the lightning_core out of my info.yml and tried to reinstall drupal and got this:

Starting Drupal installation. This takes a while. Consider using the --notify global option.                                                               [ok]
exception 'Drupal\Core\Config\UnmetDependenciesException' with message 'Configuration objects provided by <em class="placeholder">umg_brand</em> have unmet[error]
dependencies: <em class="placeholder">user.role.umg_employee (lightning_core)</em>' in
/Users/palmerd/Sites/asf8/docroot/core/lib/Drupal/Core/Config/UnmetDependenciesException.php:98

Seems like its trying to create my custom user role and is missing a dependency from lightning core.

**Comment by balsama** [comment] 2017-05-11 01:10
Ok, so it sounds to me like umg_brand itself has some dependency issues. And it's tough to troubleshoot those after-the-fact. Likely, some of the config in umg_brand is missing dependencies on config - and we're making up for that by trying make the module itself depend on the module that provides the config.

Some ideas:

**Move to config/optional**
One possible solution is to move all of umg_brand's config to /config/optional since config/optional is negotiated after install of everything is complete. While not wrong, that doesn't really solve the underlying problem, though.

**Move exclusively to install hook**
Is umg_brand a dependency of the profile? If so, removing it from there and moving it exclusively to the be installed as part of the profile's install hook might work too. But, again, this doesn't address the (probably) underlying problem.

**Re-export all config**
If you can get the entire site up and running doing what you're doing now, another approach might be to leverage features to re-export all of your modules' config once its up and running. It should do a good job of pointing to the proper config dependencies. (Even if you used it originally, it should do a better job now than it did 6 months or a year ago)

**Comment by dgpalmer** [comment] 2017-05-11 01:13
I like the 3rd option you gave, I will try to re-export all my configs and update them in the config/install. Much of the stuff in there right now is from 6 months ago or so. I will try this and let you know.

Thanks for your help Adam!

**Comment by balsama** [comment] 2017-05-11 01:56
godspeed :/

**Comment by balsama** [comment] 2017-05-24 15:02
I'm not convinced that there isn't a bug here somewhere still... especially with people migrating sites that used the extend file. But I can't find steps to reproduce, and the migrations should be slowing down. Closing this for now.

**Closed by balsama** 2017-05-24 15:02 UTC
